#!/usr/bin/env bash
IMGNAME=nom
PORT=8000

if [[ "$(docker images -q $IMGNAME 2> /dev/null)" == "" ]]; then
	echo 'Building nom image locally...'
	docker build -t nom .
	echo 'Nom image built.'
fi

if [ $# -gt 1 ]; then
	VOL=$(pwd)/$2
	echo $VOL
	if [ $1 == 'browse' ]; then
		CONT_CMD="nom $@ && cd /tmp/nom/$2 && python -m http.server $PORT"
		echo "Serving at http://localhost:$PORT..."
		docker run -p $PORT:$PORT -v $VOL:/app/$2 $IMGNAME /bin/bash -c "$CONT_CMD"
	fi
	if [ $1 == 'view' ]; then
		docker run -it -v $VOL:/app/$2 $IMGNAME /bin/bash
	fi
fi

docker run $IMGNAME nom $@


